name: linting

on:
    - push

jobs:
  lint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
      
      - name: Run pylint on src
        run: uvx pylint src/
      
      - name: Run pylint on tests
        run: uvx pylint tests/
